<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Services\ProductAggregator.cs\**" />
    <EmbeddedResource Remove="Services\ProductAggregator.cs\**" />
    <None Remove="Services\ProductAggregator.cs\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DTO\ProductManagement.DTO.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
